engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
exclude_paths:
  - "coverage/**/*"
  - "node_modules/**/*"
ratings:
  paths:
    - "**.js"
